language: python

before_install:
  - sudo apt install software-properties-common -y
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt install python3.7 terraform -y
addons:
  apt:
    update: true

deploy:
  provider: script
  script: bash deployment/setup.sh $DAISY_USERNAME $DAISY_PASSWORD $HUBSPOT_CLIENT_ID $HUBSPOT_CLIENT_SECRET
  on:
    branch: master