language: python
sudo: required
dist: xenial
python: "3.7"

before_install:
  - sudo apt-get install unzip
  - wget https://releases.hashicorp.com/terraform/${TERRAFORM}/terraform_${TERRAFORM}_linux_amd64.zip
  - unzip terraform_${TERRAFORM}_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - terraform --version
  - chmod +x deployment/setup.sh
addons:
  apt:
    update: true

install: ./deployment/setup.sh $DAISY_USERNAME $DAISY_PASSWORD $HUBSPOT_CLIENT_ID $HUBSPOT_CLIENT_SECRET

after_success:
  - echo "Success"
after_failure:
  - echo "Failure"